theme                    : minimal-mistakes-jekyll
minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

#Site Settings
locale                   : "en-US"
title                    : "myblogtest"
title_separator          : "-"
subtitle                 : "A test"
name                     : &name "Lan Hu" # &name is a YAML anchor which can be *referenced later
description              : &description "blalblalbalal"
url                      : https://shikon.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "/" # the subpath of your site, e.g. "/blog"
repository               : "shikon/shikon.github.io"